name: CI Build All Images

on:
  push:
    paths:
      - ".github/workflows/**"
      - "scripts/**"
      - "Dockerfile"
      - "makefile"
  workflow_dispatch:

jobs:
  build-images:
    name: "Build & Push Images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: ["node", "java", "go", "python", "dotnet"]

    steps:
      - uses: actions/checkout@v2

      # Build with non-root user
      - run: make ${{ matrix.name }}
      # Build with root user
      - run: make ${{ matrix.name }} IMAGE_USER=root IMAGE_USERHOME=/root IMAGE_TAG=root

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Push non-root user image
      - run: make push IMAGE_NAME=${{ matrix.name }}
      # Push root user image
      - run: make push IMAGE_NAME=${{ matrix.name }} IMAGE_TAG=root
