name: CI Build All Images

on:
  push:

jobs:
  build:
    name: "Build & Push Images"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make image-all
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: make push-all
