name: CI Build All Images

on:
  push:

jobs:
  build:
    name: "Build & Push Images"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Non root
      - run: make all
      # Root
      - run: make all IMAGE_USER=root IMAGE_USERHOME=/root IMAGE_TAG=root
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Non root
      - run: make push-all
      # Root
      - run: make push-all IMAGE_TAG=root
